/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VotacoesRouteImport } from './routes/votacoes'
import { Route as ProposicoesRouteImport } from './routes/proposicoes'
import { Route as MinhaAreaRouteImport } from './routes/minha-area'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AnaliseRouteImport } from './routes/analise'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParlamentaresIndexRouteImport } from './routes/parlamentares.index'
import { Route as MinhaAreaIndexRouteImport } from './routes/minha-area.index'
import { Route as ProposicoesIdRouteImport } from './routes/proposicoes.$id'
import { Route as ParlamentaresIdRouteImport } from './routes/parlamentares.$id'
import { Route as MinhaAreaMeusVotosRouteImport } from './routes/minha-area.meus-votos'
import { Route as MinhaAreaConfiguracoesRouteImport } from './routes/minha-area.configuracoes'
import { Route as MinhaAreaAlertasRouteImport } from './routes/minha-area.alertas'
import { Route as MinhaAreaAcompanhadosRouteImport } from './routes/minha-area.acompanhados'

const VotacoesRoute = VotacoesRouteImport.update({
  id: '/votacoes',
  path: '/votacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposicoesRoute = ProposicoesRouteImport.update({
  id: '/proposicoes',
  path: '/proposicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaAreaRoute = MinhaAreaRouteImport.update({
  id: '/minha-area',
  path: '/minha-area',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseRoute = AnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParlamentaresIndexRoute = ParlamentaresIndexRouteImport.update({
  id: '/parlamentares/',
  path: '/parlamentares/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaAreaIndexRoute = MinhaAreaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MinhaAreaRoute,
} as any)
const ProposicoesIdRoute = ProposicoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProposicoesRoute,
} as any)
const ParlamentaresIdRoute = ParlamentaresIdRouteImport.update({
  id: '/parlamentares/$id',
  path: '/parlamentares/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaAreaMeusVotosRoute = MinhaAreaMeusVotosRouteImport.update({
  id: '/meus-votos',
  path: '/meus-votos',
  getParentRoute: () => MinhaAreaRoute,
} as any)
const MinhaAreaConfiguracoesRoute = MinhaAreaConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => MinhaAreaRoute,
} as any)
const MinhaAreaAlertasRoute = MinhaAreaAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => MinhaAreaRoute,
} as any)
const MinhaAreaAcompanhadosRoute = MinhaAreaAcompanhadosRouteImport.update({
  id: '/acompanhados',
  path: '/acompanhados',
  getParentRoute: () => MinhaAreaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/login': typeof LoginRoute
  '/metodologia': typeof MetodologiaRoute
  '/minha-area': typeof MinhaAreaRouteWithChildren
  '/proposicoes': typeof ProposicoesRouteWithChildren
  '/votacoes': typeof VotacoesRoute
  '/minha-area/acompanhados': typeof MinhaAreaAcompanhadosRoute
  '/minha-area/alertas': typeof MinhaAreaAlertasRoute
  '/minha-area/configuracoes': typeof MinhaAreaConfiguracoesRoute
  '/minha-area/meus-votos': typeof MinhaAreaMeusVotosRoute
  '/parlamentares/$id': typeof ParlamentaresIdRoute
  '/proposicoes/$id': typeof ProposicoesIdRoute
  '/minha-area/': typeof MinhaAreaIndexRoute
  '/parlamentares/': typeof ParlamentaresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/login': typeof LoginRoute
  '/metodologia': typeof MetodologiaRoute
  '/proposicoes': typeof ProposicoesRouteWithChildren
  '/votacoes': typeof VotacoesRoute
  '/minha-area/acompanhados': typeof MinhaAreaAcompanhadosRoute
  '/minha-area/alertas': typeof MinhaAreaAlertasRoute
  '/minha-area/configuracoes': typeof MinhaAreaConfiguracoesRoute
  '/minha-area/meus-votos': typeof MinhaAreaMeusVotosRoute
  '/parlamentares/$id': typeof ParlamentaresIdRoute
  '/proposicoes/$id': typeof ProposicoesIdRoute
  '/minha-area': typeof MinhaAreaIndexRoute
  '/parlamentares': typeof ParlamentaresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/login': typeof LoginRoute
  '/metodologia': typeof MetodologiaRoute
  '/minha-area': typeof MinhaAreaRouteWithChildren
  '/proposicoes': typeof ProposicoesRouteWithChildren
  '/votacoes': typeof VotacoesRoute
  '/minha-area/acompanhados': typeof MinhaAreaAcompanhadosRoute
  '/minha-area/alertas': typeof MinhaAreaAlertasRoute
  '/minha-area/configuracoes': typeof MinhaAreaConfiguracoesRoute
  '/minha-area/meus-votos': typeof MinhaAreaMeusVotosRoute
  '/parlamentares/$id': typeof ParlamentaresIdRoute
  '/proposicoes/$id': typeof ProposicoesIdRoute
  '/minha-area/': typeof MinhaAreaIndexRoute
  '/parlamentares/': typeof ParlamentaresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analise'
    | '/login'
    | '/metodologia'
    | '/minha-area'
    | '/proposicoes'
    | '/votacoes'
    | '/minha-area/acompanhados'
    | '/minha-area/alertas'
    | '/minha-area/configuracoes'
    | '/minha-area/meus-votos'
    | '/parlamentares/$id'
    | '/proposicoes/$id'
    | '/minha-area/'
    | '/parlamentares/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analise'
    | '/login'
    | '/metodologia'
    | '/proposicoes'
    | '/votacoes'
    | '/minha-area/acompanhados'
    | '/minha-area/alertas'
    | '/minha-area/configuracoes'
    | '/minha-area/meus-votos'
    | '/parlamentares/$id'
    | '/proposicoes/$id'
    | '/minha-area'
    | '/parlamentares'
  id:
    | '__root__'
    | '/'
    | '/analise'
    | '/login'
    | '/metodologia'
    | '/minha-area'
    | '/proposicoes'
    | '/votacoes'
    | '/minha-area/acompanhados'
    | '/minha-area/alertas'
    | '/minha-area/configuracoes'
    | '/minha-area/meus-votos'
    | '/parlamentares/$id'
    | '/proposicoes/$id'
    | '/minha-area/'
    | '/parlamentares/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnaliseRoute: typeof AnaliseRoute
  LoginRoute: typeof LoginRoute
  MetodologiaRoute: typeof MetodologiaRoute
  MinhaAreaRoute: typeof MinhaAreaRouteWithChildren
  ProposicoesRoute: typeof ProposicoesRouteWithChildren
  VotacoesRoute: typeof VotacoesRoute
  ParlamentaresIdRoute: typeof ParlamentaresIdRoute
  ParlamentaresIndexRoute: typeof ParlamentaresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/votacoes': {
      id: '/votacoes'
      path: '/votacoes'
      fullPath: '/votacoes'
      preLoaderRoute: typeof VotacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposicoes': {
      id: '/proposicoes'
      path: '/proposicoes'
      fullPath: '/proposicoes'
      preLoaderRoute: typeof ProposicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-area': {
      id: '/minha-area'
      path: '/minha-area'
      fullPath: '/minha-area'
      preLoaderRoute: typeof MinhaAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise': {
      id: '/analise'
      path: '/analise'
      fullPath: '/analise'
      preLoaderRoute: typeof AnaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parlamentares/': {
      id: '/parlamentares/'
      path: '/parlamentares'
      fullPath: '/parlamentares/'
      preLoaderRoute: typeof ParlamentaresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-area/': {
      id: '/minha-area/'
      path: '/'
      fullPath: '/minha-area/'
      preLoaderRoute: typeof MinhaAreaIndexRouteImport
      parentRoute: typeof MinhaAreaRoute
    }
    '/proposicoes/$id': {
      id: '/proposicoes/$id'
      path: '/$id'
      fullPath: '/proposicoes/$id'
      preLoaderRoute: typeof ProposicoesIdRouteImport
      parentRoute: typeof ProposicoesRoute
    }
    '/parlamentares/$id': {
      id: '/parlamentares/$id'
      path: '/parlamentares/$id'
      fullPath: '/parlamentares/$id'
      preLoaderRoute: typeof ParlamentaresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-area/meus-votos': {
      id: '/minha-area/meus-votos'
      path: '/meus-votos'
      fullPath: '/minha-area/meus-votos'
      preLoaderRoute: typeof MinhaAreaMeusVotosRouteImport
      parentRoute: typeof MinhaAreaRoute
    }
    '/minha-area/configuracoes': {
      id: '/minha-area/configuracoes'
      path: '/configuracoes'
      fullPath: '/minha-area/configuracoes'
      preLoaderRoute: typeof MinhaAreaConfiguracoesRouteImport
      parentRoute: typeof MinhaAreaRoute
    }
    '/minha-area/alertas': {
      id: '/minha-area/alertas'
      path: '/alertas'
      fullPath: '/minha-area/alertas'
      preLoaderRoute: typeof MinhaAreaAlertasRouteImport
      parentRoute: typeof MinhaAreaRoute
    }
    '/minha-area/acompanhados': {
      id: '/minha-area/acompanhados'
      path: '/acompanhados'
      fullPath: '/minha-area/acompanhados'
      preLoaderRoute: typeof MinhaAreaAcompanhadosRouteImport
      parentRoute: typeof MinhaAreaRoute
    }
  }
}

interface MinhaAreaRouteChildren {
  MinhaAreaAcompanhadosRoute: typeof MinhaAreaAcompanhadosRoute
  MinhaAreaAlertasRoute: typeof MinhaAreaAlertasRoute
  MinhaAreaConfiguracoesRoute: typeof MinhaAreaConfiguracoesRoute
  MinhaAreaMeusVotosRoute: typeof MinhaAreaMeusVotosRoute
  MinhaAreaIndexRoute: typeof MinhaAreaIndexRoute
}

const MinhaAreaRouteChildren: MinhaAreaRouteChildren = {
  MinhaAreaAcompanhadosRoute: MinhaAreaAcompanhadosRoute,
  MinhaAreaAlertasRoute: MinhaAreaAlertasRoute,
  MinhaAreaConfiguracoesRoute: MinhaAreaConfiguracoesRoute,
  MinhaAreaMeusVotosRoute: MinhaAreaMeusVotosRoute,
  MinhaAreaIndexRoute: MinhaAreaIndexRoute,
}

const MinhaAreaRouteWithChildren = MinhaAreaRoute._addFileChildren(
  MinhaAreaRouteChildren,
)

interface ProposicoesRouteChildren {
  ProposicoesIdRoute: typeof ProposicoesIdRoute
}

const ProposicoesRouteChildren: ProposicoesRouteChildren = {
  ProposicoesIdRoute: ProposicoesIdRoute,
}

const ProposicoesRouteWithChildren = ProposicoesRoute._addFileChildren(
  ProposicoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnaliseRoute: AnaliseRoute,
  LoginRoute: LoginRoute,
  MetodologiaRoute: MetodologiaRoute,
  MinhaAreaRoute: MinhaAreaRouteWithChildren,
  ProposicoesRoute: ProposicoesRouteWithChildren,
  VotacoesRoute: VotacoesRoute,
  ParlamentaresIdRoute: ParlamentaresIdRoute,
  ParlamentaresIndexRoute: ParlamentaresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
